#!/bin/bash

# Prüfen, ob beide Parameter übergeben wurden
if [ -z "$1" ] || [ -z "$2" ]; then
  echo "Fehler: Bitte URL und Zielordner angeben!"
  echo "Nutzung: $0 <URL> <Zielordner>"
  exit 1
fi

yt-dlp -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0 --yes-playlist -P "$2" -o "%(title)s.%(ext)s" "$1"
