#!/bin/bash

# Set path to the wallpaper directory
wallpapers_dir="$HOME/Bilder/wallpapers"

show_help() {
    echo "walset - Wallpaper Management Tool"
    echo ""
    echo "USAGE:"
    echo "  walset [OPTION|IMAGE-PATH]"
    echo ""
    echo "OPTIONS:"
    echo "  random          Set a random wallpaper from the wallpaper directory"
    echo "  -l              List all available wallpapers"
    echo "  -h, --help      Display this help message"
    echo "  <IMAGE-PATH>    Set a specific image as wallpaper"
    echo ""
}

case "$1" in
  --help|-h)
    show_help
    exit 0
    ;;
  -l)
    echo "Available wallpapers in '$wallpapers_dir':"
    find "$wallpapers_dir" -type f \( -iname "*.jpg" -o -iname "*.png" -o -iname "*.jpeg" \) -exec basename {} \;
    exit 0
    ;;
  random|"")
    img=$(find "$wallpapers_dir" -type f \( -iname "*.jpg" -o -iname "*.png" -o -iname "*.jpeg" \) | shuf -n 1)
    ;;
  *)

    if [[ "$1" = /* ]]; then
        img="$1"
    else
        img="$wallpapers_dir/$1"
    fi
    ;;
esac

# Validierung
if [ -z "$img" ]; then
  echo "No images found."
  exit 1
fi

if [ ! -f "$img" ]; then
  echo "Error: Image '$img' not found."
  exit 1
fi

# Set the selected image as the wallpaper
# See https://iniox.github.io/#matugen/configuration for config
matugen image "$img" --source-color-index 0