# HyprEmoji Configuration

# Keybind to open hypremoji
bind = SUPER, period, exec, hypremoji

windowrule = size 410 391, match:title ^(HyprEmoji)$
windowrule = move 1501 646, match:title ^(HyprEmoji)$
windowrule = float true, match:title ^(HyprEmoji)$
