#!/usr/bin/env bash

cd ~
if [ $# -eq 0 ]; then
    fd --type f --hidden \
   --exclude '**/vivaldi/**' \
   --exclude '**/vesktop/**' \
   --exclude '**/firefox/**' \
   --exclude '**/Bilder/Bilder/**' \
   . Dokumente Downloads Schreibtisch Musik .config .bashrc
else
    coproc ( xdg-open "$1" > /dev/null 2>&1 )
fi