#!/usr/bin/env bash

cd ~
if [ $# -eq 0 ]; then
    fd --type f --hidden \
       --exclude .git \
       --exclude .cache \
       --exclude node_modules \
       --exclude .local/share/\
       --exclude .local/state \
       --exclude .vivaldi \
       .
else
    coproc ( xdg-open "$1" > /dev/null 2>&1 )
fi